apiVersion: v1
kind: Service
metadata:
  name: gripss-webserver-service
  namespace: default
spec:
  selector:
    app: gripss-webserver # This should match the label of your pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Flask app is running on this port inside the pod
      nodePort: 30080
  type: NodePort
