apiVersion: v1
kind: Service
metadata:
  name: gripss-webserver-service
  namespace: default
spec:
  selector:
    app: gripss-webserver  # Assuming this label selects your pods
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080  # This is the port on each node. It's in the range 30000-32767.
  type: NodePort
